### ISSUE TITLE
Turning the nubots account into an organisation

### ISSUE THREAD

**Issue by BrendanAnnable** [NUbots/robocup#15]
I just noticed the nubots account is actually just a normal account.

I suggest turning it into an organisation! That way we can have administrative rights and teams and all things that are good.

It allows us to manage admins and give (or take) specific permissions out to other users, rather than all logging in under the nubots account and making changes there.

There is a button that turns it into an org so it isn't a big deal.

Thoughts?

**Comment by BrendanAnnable** [comment]
@josiahw

**Comment by josiahw** [comment]
hmm... Maybe. I'll let you know.
