### ISSUE TITLE
Review NUData and NUActionatorsData

### ISSUE THREAD

**Issue by mmetcalfe** [NUbots/robocup#34]
These classes kind of bloated. There's a fair bit I'm not too fond of here.
(a bunch of stuff about the Actionators in general looks a little questionable at the moment)

I feel that we should review these classes after Robocup, and look into making them neater and clearer.

**Comment by josiahw** [comment]
Sounds good. The SENG FYP guys arelooking at re-factoring our code after robocup (to include their new data/message passing system). We should work with them to remove as much crap as possible.
