### ISSUE TITLE
The configuration of Robot 1 should be copied to the other robots

### ISSUE THREAD

**Issue by mmetcalfe** [NUbots/robocup#42]
Changes have been made to Robot 1's configuration that have improved its performance.
The other robots need to have the newer configuration.

The robots configuration should be put under source control.

**Comment by shannonfenn** [comment]
What configuration? The standard configuration folders are part of the repository and can be copied onto the robots using make DarwinConfigInstall (though I'm not sure if that script copies the entire contents of the folder or just known config files - in which case it would need an update)

**Comment by josiahw** [comment]
the robots' configuration is under source control. Check robocup/Config -
that's the default configuration files. Add #1's changes there and then do
make DarwinConfigInstall with the latest repository
