### ISSUE TITLE
We're not using Git Issues (at all)

### ISSUE THREAD

**Issue by mmetcalfe** [NUbots/robocup#5]
Using this issue system seems fairly worthwhile.  It could help keep track of important things that more than just one or two team members need to know about, + seems more efficient/reliable than leaving post-it-notes on things / the lab's blackboard / facebook (although they all have their uses).

Any thoughts?

**Comment by shannonfenn** [comment]
I'm for it.

**Comment by ghost** [comment]
Check out Atlassian JIRA. Really awesome browser interface, and free for open source projects.

**Comment by ghost** [comment]
http://www.atlassian.com/software/jira/pricing/?tab=download

**Comment by WongAaronSW** [comment]
Github functions:
- Blame function. Use public shame to drive productivity
- To-do lists.
- wiki

Sent from my HTC

----- Reply message -----

**Comment by BrendanAnnable** [comment]
Added some milestones and issues!
