### ISSUE TITLE
OS + VM needs updating

### ISSUE THREAD

**Issue by BrendanAnnable** [NUbots/robocup#7]
Being well behind the latest, I'm sure everyone would love these to be updated to a recent OS just so we can use package managers.

Current candidate is Xubuntu. I think Gentoo was also suggested.

If anyone else has a suggestion, please say!

Upgrade strategy:
- backup the VM
- install a new VM using Xubuntu and get compiling working
- backup the robot (create a disk image)
- install a new OS on the robot
- get the compiled binary working

**Comment by josiahw** [comment]
realistically, we should use a non-ubuntu OS. Team Darwin uses arch, but a basic debian (so we could access ubuntu repositories) would also work. We really want as few system processes as possible other than basic X11 and wifi connectivity,

**Comment by StevenNicklin** [comment]
I still have a image of Linux Mint for the Darwin that I got from the Robotis guy at RoboCup if you're interested in that.

**Comment by mmetcalfe** [comment]
I like the sound of Xubuntu from a productivity/ease of use standpoint (more similar to what people use/are used to, + more modern = better).
Couldn't we just kill unnecessary processes before a game?

(that said, anything modern enough to remove the need to compile from a VM would make development considerably faster/easier)

**Comment by ghost** [comment]
C++ is platform dependent which is why I think we need the VM. I second the Xubuntu idea for ease of use, but Josiah raises a good point with it having too many unnecessary things running.

**Comment by TrentHouliston** [comment]
Lubuntu might be ok... it is supposed to be a lightweight ubuntu after all http://lubuntu.net/

Or better yet install the command line system version from the alternate CD of Ubuntu, that installs nothing other then the bare OS, then you could add on other packages on demand

**Comment by TrentHouliston** [comment]
Even better... https://help.ubuntu.com/community/Installation/MinimalCD

**Comment by josiahw** [comment]
we have no cd drive :D

**Comment by TrentHouliston** [comment]
thats what USB is for! :P

I just installed it, this is a list of packages the CLI version installs for 12.10
http://pastebin.com/ChNDw4D1

**Comment by josiahw** [comment]
OK, let's try 12.04 LTS from: https://help.ubuntu.com/community/Installation/MinimalCD

**Comment by BrendanAnnable** [comment]
Started installing 12.04 LTS on darwin1 today, had some issues where the install would install grub onto the USB drive I was installing from... I'll try again next week!

**Comment by BrendanAnnable** [comment]
Got the code compiliing on a VM with GCC 4.6, how did you end up installing GCC 4.7 on Ubuntu 12.04 @Hamish256?

**Comment by josiahw** [comment]
http://askubuntu.com/questions/271388/how-to-install-gcc-4-8-in-ubuntu-12-04-from-the-terminalseems
easy enough?

**Comment by BrendanAnnable** [comment]
Tempted just to install 12.10 if we are going to use test toolchains?

I'll be making an install script anyway.

**Comment by mmetcalfe** [comment]
I use 12.10, so i just installed GCC with something like:
    $ apt-get install gcc-4.7-base

**Comment by BrendanAnnable** [comment]
12.10 comes with GCC 4.7 for me, unless anyone objects I'll be using it as I know the software FYP guys use nearly all of the C++ 11 features for their new architecture.

Probably also has newer versions of the libraries I'm using too.

**Comment by mmetcalfe** [comment]
Just so you know: I've been working on the CM730Errors branch, and made a few changes to the way the darwin.a library is handled.
- The Darwin's framework folder is in the git repository under '/Framework/darwin'
- There's two new build targets in the main make file to build and clean the framework
- The script that sends 'nubotbin' to the darwin has been modified to also send 'darwin.a' and a 'darwinNUbotStart' script
- The 'darwinNUbotStart' script is intended to be run on the robot instead of running nubotbin. It simply exports LD_LIBRARY_PATH as the location to which the 'darwin.a' library was sent, then runs 'nubotbin'

It all seems to work, but my slightly refactored framework code hasn't really been tested, because the robot had motor issues on Friday.

I think we should push something like this to the master branch, to remove the need to manually manage darwin.a on each robot.
(since we're updating the OS, it seems like a good time to make these kinds of changes.
Perhaps i should make a related issue instead of commenting here...)

**Comment by shannonfenn** [comment]
Damn, I've intentionally not been using those features due to our old as 
hell OS.

**Comment by shannonfenn** [comment]
Sounds like an excellent solution, as long as it has been tested I'm 
personally happy for it to go up to the mainline, but I'll leave the 
final decision to Jo (as all major ones should be).

Is the new build target for the framework code a dependency of the 
makeDarwin target?

**Comment by mmetcalfe** [comment]
Currently it's not, because changes to the framework are fairly rare, but it could be made so.
A clean build of darwin.a doesn't take very long anyway, so adding it to the makeDarwin target couldn't really hurt.

**Comment by shannonfenn** [comment]
Probably good, otherwise someone unaware could get a clean robot without 
darwin.a in the correct location for darwinNUbotStart - unlikely and 
easy to solve but potentially a bit of a nightmare for a new student.

**Comment by BrendanAnnable** [comment]
Spoke with the software guys, they're apparently using 12.04 and recommend I also do so. I've got gcc 4.7 working on it as well so I'm sticking with 12.04.

@Hamish256  sounds amazing! and yeah I'd make a new issue just for that feature :)

**Comment by BrendanAnnable** [comment]
Is anyone aware if software is needed for the low-battery warning alarm?

**Comment by BrendanAnnable** [comment]
Turns out low-battery warning alarm is built-in, did not need to be installed.

I'm closing this issue as all that is left is to update the robots with the new OS which is issue #19
